language: java

jdk:
  - openjdk14

sudo: false

env:
  global:

    - CODECOV_TOKEN="689fac63-a752-449d-81e9-4fb8190af32e"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - marikakopina@gmail.com
    on_success: never # default: change
    on_failure: always # default: always